### ISSUE TITLE
Engine currently broken

### ISSUE THREAD

**Issue by npfoss** [jrburga/VGEngine#6]
`AttributeError: 'NoneType' object has no attribute 'body'` when running any game with `play.py`.

The working commit I upgraded from when things broke was 13c2b794e9585a815dab6f57be87c5bda1352033

**Comment by jrburga** [comment]
Uh oh...

Checkout a later version in the mean time. I'll revert the commit and fix
the change on a separate branch

**Comment by jrburga** [comment]
Fixed it in latest commit
